/**
 * Node type definitions for the workflow designer.
 * Maps to the engine plugin system.
 */

export const NODE_DEFINITIONS = [
  {
    type: 'start',
    label: 'Start',
    category: 'Flow Control',
    description: 'Workflow entry point',
    iconKey: 'play',
    color: '#16A34A',
    defaults: {},
    schema: [],
    maxInstances: 1,
    hasInput: false,
    hasOutput: true,
  },
  {
    type: 'openBrowser',
    label: 'Open Browser',
    category: 'Browser',
    description: 'Launch a browser instance',
    iconKey: 'globe',
    color: '#2563EB',
    defaults: { headless: false, profileMode: 'isolated', userDataDir: '' },
    schema: [
      { key: 'profileMode', label: 'Profile Mode', type: 'select', options: ['isolated', 'user'],
        hint: 'isolated = fresh clean session. user = persistent profile (keeps logins, cookies, extensions).' },
      { key: 'userDataDir', label: 'User Data Dir (optional)', type: 'text', placeholder: 'blank = managed profile',
        hint: 'Only for "user" mode. Leave blank to use the app-managed profile.' },
      { key: 'headless', label: 'Headless Mode', type: 'boolean' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'navigateUrl',
    label: 'Navigate URL',
    category: 'Browser',
    description: 'Go to a web address',
    iconKey: 'link',
    color: '#7C3AED',
    defaults: { url: 'https://example.com' },
    schema: [
      { key: 'url', label: 'URL', type: 'text', placeholder: 'https://example.com' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'inputText',
    label: 'Input Text',
    category: 'Input',
    description: 'Type into an input field',
    iconKey: 'type',
    color: '#D97706',
    defaults: { selector: '', value: '', clearFirst: true },
    schema: [
      { key: 'selector',   label: 'CSS Selector',    type: 'text',    placeholder: '#username', isSelector: true },
      { key: 'value',      label: 'Value',            type: 'text',    placeholder: 'Enter text...' },
      { key: 'clearFirst', label: 'Clear Field First',type: 'boolean' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'clickElement',
    label: 'Click Element',
    category: 'Mouse',
    description: 'Click a page element',
    iconKey: 'mouse',
    color: '#7C3AED',
    defaults: { selector: '', doubleClick: false, waitNavigation: false },
    schema: [
      { key: 'selector',       label: 'CSS Selector',       type: 'text',    placeholder: '#login-button', isSelector: true },
      { key: 'doubleClick',    label: 'Double Click',        type: 'boolean' },
      { key: 'waitNavigation', label: 'Wait for Navigation', type: 'boolean',
        hint: 'Enable when this click triggers a redirect or page reload.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'end',
    label: 'End',
    category: 'Flow Control',
    description: 'Workflow end point',
    iconKey: 'stop',
    color: '#6B7280',
    defaults: { autoCloseBrowser: true, restoreWindow: true },
    schema: [
      { key: 'autoCloseBrowser', label: 'Auto Close Browser',    type: 'boolean',
        hint: 'When disabled, the browser stays open after the workflow finishes.' },
      { key: 'restoreWindow',    label: 'Restore Cyclone Window', type: 'boolean',
        hint: 'Bring Cyclone back to the foreground after execution.' },
    ],
    maxInstances: 1,
    hasInput: true,
    hasOutput: false,
  },

  // ── Stage 2 nodes ─────────────────────────────────────────
  {
    type: 'setVariable',
    label: 'Set Variable',
    category: 'Logic',
    description: 'Assign a value to a workflow variable',
    iconKey: 'variable',
    color: '#16A34A',
    defaults: { variableName: '', value: '' },
    schema: [
      { key: 'variableName', label: 'Variable Name', type: 'text',
        placeholder: 'username' },
      { key: 'value', label: 'Value', type: 'text',
        placeholder: 'admin',
        hint: 'Plain text, {{variable}}, or typed literals: {{[1,2,3]}} {{true}} {{42}} {{response.data}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'logMessage',
    label: 'Log Message',
    category: 'Logic',
    description: 'Print a message to the execution console',
    iconKey: 'log',
    color: '#6B7280',
    defaults: { message: '', level: 'INFO' },
    schema: [
      { key: 'message', label: 'Message', type: 'textarea',
        placeholder: 'Hello, {{username}}',
        hint: 'Supports {{variable}} and {{obj.nested}} interpolation.' },
      { key: 'level', label: 'Level', type: 'text',
        placeholder: 'INFO',
        hint: 'INFO, WARN, ERROR, or SUCCESS.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'delay',
    label: 'Delay',
    category: 'Logic',
    description: 'Pause execution for a number of milliseconds',
    iconKey: 'clock',
    color: '#D97706',
    defaults: { milliseconds: '1000' },
    schema: [
      { key: 'milliseconds', label: 'Milliseconds', type: 'text',
        placeholder: '1000',
        hint: 'Supports {{variable}} — resolved at runtime.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'httpRequest',
    label: 'HTTP Request',
    category: 'API',
    description: 'Make an HTTP call and store the response',
    iconKey: 'api',
    color: '#2563EB',
    defaults: { method: 'GET', url: '', headers: '', body: '', outputVariable: 'response' },
    schema: [
      { key: 'method', label: 'Method', type: 'text',
        placeholder: 'GET' },
      { key: 'url', label: 'URL', type: 'text',
        placeholder: 'https://api.example.com/users/{{userId}}',
        hint: 'Supports {{variable}} interpolation.' },
      { key: 'headers', label: 'Headers (JSON)', type: 'textarea',
        placeholder: '{"Authorization": "Bearer {{token}}"}',
        hint: 'Optional JSON object. Supports {{variable}}.' },
      { key: 'body', label: 'Body (JSON)', type: 'textarea',
        placeholder: '{"username": "{{username}}"}',
        hint: 'Used for POST / PUT / PATCH. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'response',
        hint: 'Access response data with {{response.data.id}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 3 nodes ─────────────────────────────────────────
  {
    type: 'ifNode',
    label: 'IF',
    category: 'Logic',
    description: 'Branch workflow based on a condition',
    iconKey: 'condition',
    color: '#7C3AED',
    defaults: { condition: '' },
    schema: [
      { key: 'condition', label: 'Condition', type: 'text',
        placeholder: '{{response.status == 200}}',
        hint: 'Supports {{variable}} expressions. Routes to TRUE or FALSE branch.' },
    ],
    hasInput: true,
    hasOutput: false,
    outputHandles: [
      { id: 'true',  label: 'TRUE',  color: '#16A34A' },
      { id: 'false', label: 'FALSE', color: '#DC2626' },
    ],
  },
  {
    type: 'forEachNode',
    label: 'For Each',
    category: 'Logic',
    description: 'Iterate over each item in a collection',
    iconKey: 'loop',
    color: '#2563EB',
    defaults: { collection: '', itemVariable: 'item' },
    schema: [
      { key: 'collection',   label: 'Collection',   type: 'text',
        placeholder: '{{users}}',
        hint: 'Variable containing an array. Use {{variable}} syntax.' },
      { key: 'itemVariable', label: 'Item Variable', type: 'text',
        placeholder: 'item',
        hint: 'Name for each element (e.g. access with {{item.name}}).' },
    ],
    hasInput: true,
    hasOutput: false,
    outputHandles: [
      { id: 'body', label: 'BODY', color: '#2563EB' },
      { id: 'done', label: 'DONE', color: '#16A34A' },
    ],
  },
  {
    type: 'tryCatchNode',
    label: 'Try / Catch',
    category: 'Logic',
    description: 'Handle errors without stopping the workflow',
    iconKey: 'shield',
    color: '#D97706',
    defaults: { errorVariable: 'lastError' },
    schema: [
      { key: 'errorVariable', label: 'Error Variable', type: 'text',
        placeholder: 'lastError',
        hint: 'Variable that stores the error message if TRY fails.' },
    ],
    hasInput: true,
    hasOutput: false,
    outputHandles: [
      { id: 'try',   label: 'TRY',   color: '#16A34A' },
      { id: 'catch', label: 'CATCH', color: '#DC2626' },
    ],
  },

  // ── Stage 4A — Browser Wait ────────────────────────────────
  {
    type: 'waitUrl',
    label: 'Wait URL',
    category: 'Browser Wait',
    description: 'Wait until the page URL contains the expected value',
    iconKey: 'waitUrl',
    color: '#7C3AED',
    defaults: { expectedUrl: '', timeout: '15000' },
    schema: [
      { key: 'expectedUrl', label: 'Expected URL', type: 'text',
        placeholder: 'https://example.com/success',
        hint: 'Partial match — waits until current URL contains this string. Supports {{variable}}.' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'text', placeholder: '15000' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'waitElement',
    label: 'Wait Element',
    category: 'Browser Wait',
    description: 'Wait until an element reaches a specific state',
    iconKey: 'waitEl',
    color: '#7C3AED',
    defaults: { selector: '', state: 'visible', timeout: '10000' },
    schema: [
      { key: 'selector', label: 'CSS Selector', type: 'text',
        placeholder: '#success-message', isSelector: true },
      { key: 'state',    label: 'State',        type: 'text',
        placeholder: 'visible', hint: 'visible | attached | hidden | detached' },
      { key: 'timeout',  label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'waitPageLoad',
    label: 'Wait Page Load',
    category: 'Browser Wait',
    description: 'Wait for the page to reach a specific load state',
    iconKey: 'waitLoad',
    color: '#7C3AED',
    defaults: { state: 'domcontentloaded', timeout: '30000' },
    schema: [
      { key: 'state',   label: 'Load State',   type: 'text',
        placeholder: 'domcontentloaded', hint: 'load | domcontentloaded | networkidle' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'text', placeholder: '30000' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 4A — Browser Get ─────────────────────────────────
  {
    type: 'getCurrentUrl',
    label: 'Get Current URL',
    category: 'Browser Get',
    description: 'Store the current page URL in a workflow variable',
    iconKey: 'getUrl',
    color: '#2563EB',
    defaults: { outputVariable: 'currentUrl' },
    schema: [
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'currentUrl', hint: 'Access with {{currentUrl}} in later nodes.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'getText',
    label: 'Get Text',
    category: 'Browser Get',
    description: 'Extract visible text from an element into a variable',
    iconKey: 'getText',
    color: '#2563EB',
    defaults: { selector: '', outputVariable: 'text', timeout: '10000' },
    schema: [
      { key: 'selector',      label: 'CSS Selector',   type: 'text',
        placeholder: 'h1.post-title', isSelector: true },
      { key: 'outputVariable',label: 'Output Variable', type: 'text',
        placeholder: 'text', hint: 'Access extracted text with {{text}} in later nodes.' },
      { key: 'timeout',       label: 'Timeout (ms)',    type: 'text', placeholder: '10000' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'elementExists',
    label: 'Element Exists',
    category: 'Browser Get',
    description: 'Check if an element exists, store true/false in a variable',
    iconKey: 'exists',
    color: '#16A34A',
    defaults: { selector: '', outputVariable: 'elementExists' },
    schema: [
      { key: 'selector',      label: 'CSS Selector',   type: 'text',
        placeholder: '#error-message', isSelector: true },
      { key: 'outputVariable',label: 'Output Variable', type: 'text',
        placeholder: 'elementExists', hint: 'Use with IF: {{elementExists == true}}' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 5 — Data Processing ──────────────────────────────
  {
    type: 'jsonParse',
    label: 'JSON Parse',
    category: 'Data Processing',
    description: 'Parse a JSON string into an object or array',
    iconKey: 'jsonParse',
    color: '#0891B2',
    defaults: { input: '', outputVariable: 'jsonData' },
    schema: [
      { key: 'input',          label: 'JSON Input',      type: 'text',
        placeholder: '{{response.raw}}',
        hint: 'Variable or text containing a valid JSON string. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'jsonData',
        hint: 'Access with {{jsonData.key}} or {{jsonData.0.name}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'stringReplace',
    label: 'String Replace',
    category: 'Data Processing',
    description: 'Replace all occurrences of a substring',
    iconKey: 'strReplace',
    color: '#0891B2',
    defaults: { input: '', search: '', replace: '', outputVariable: 'result' },
    schema: [
      { key: 'input',          label: 'Input String',    type: 'text',
        placeholder: '{{someVariable}}',
        hint: 'Source string. Supports {{variable}}.' },
      { key: 'search',         label: 'Search',          type: 'text',
        placeholder: '-',
        hint: 'All occurrences of this substring are replaced.' },
      { key: 'replace',        label: 'Replace With',    type: 'text',
        placeholder: '',
        hint: 'Replacement text. Leave blank to delete the matched substring.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'result' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'stringContains',
    label: 'String Contains',
    category: 'Data Processing',
    description: 'Check if a string contains a substring; stores true/false',
    iconKey: 'strContains',
    color: '#0891B2',
    defaults: { input: '', search: '', caseSensitive: true, outputVariable: 'containsResult' },
    schema: [
      { key: 'input',          label: 'Input String',    type: 'text',
        placeholder: '{{someVariable}}',
        hint: 'Source string to search within. Supports {{variable}}.' },
      { key: 'search',         label: 'Search For',      type: 'text',
        placeholder: 'hello' },
      { key: 'caseSensitive',  label: 'Case Sensitive',  type: 'boolean' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'containsResult',
        hint: 'Stores true or false. Use with IF: {{containsResult == true}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'dateTimeFormat',
    label: 'Date Time Format',
    category: 'Data Processing',
    description: 'Parse and reformat a date/time string',
    iconKey: 'dateTime',
    color: '#0891B2',
    defaults: { inputDate: '', inputFormat: '', outputFormat: 'DD/MM/YYYY', outputVariable: 'formattedDate' },
    schema: [
      { key: 'inputDate',      label: 'Input Date',      type: 'text',
        placeholder: '2026-06-15',
        hint: 'Supports {{variable}}. ISO format is auto-detected when Input Format is blank.' },
      { key: 'inputFormat',    label: 'Input Format',    type: 'text',
        placeholder: 'YYYY-MM-DD',
        hint: 'Tokens: YYYY MM DD HH mm ss. Leave blank to auto-parse.' },
      { key: 'outputFormat',   label: 'Output Format',   type: 'text',
        placeholder: 'DD/MM/YYYY',
        hint: 'Tokens: YYYY MM DD HH mm ss.  e.g. DD/MM/YYYY HH:mm' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'formattedDate' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'arrayLength',
    label: 'Array Length',
    category: 'Data Processing',
    description: 'Get the number of items in an array',
    iconKey: 'arrLength',
    color: '#0891B2',
    defaults: { inputArray: '', outputVariable: 'arrayLength' },
    schema: [
      { key: 'inputArray',     label: 'Input Array',     type: 'text',
        placeholder: '{{users}}',
        hint: 'Variable containing an array. Use {{variableName}} syntax.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'arrayLength',
        hint: 'Stores the count as a number. Use with IF: {{arrayLength > 0}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 5 — File System ──────────────────────────────────
  {
    type: 'readFile',
    label: 'Read File',
    category: 'File System',
    description: 'Read file contents into a variable',
    iconKey: 'readFile',
    color: '#EA580C',
    defaults: { filePath: '', encoding: 'utf8', outputVariable: 'fileContent' },
    schema: [
      { key: 'filePath',       label: 'File Path',       type: 'text',
        placeholder: './data/input.json',
        hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'encoding',       label: 'Encoding',        type: 'text',
        placeholder: 'utf8', hint: 'utf8 (default) | ascii | base64 | binary' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'fileContent',
        hint: 'File contents stored as a string. Combine with JSON Parse for JSON files.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'writeFile',
    label: 'Write File',
    category: 'File System',
    description: 'Write or append content to a file',
    iconKey: 'writeFile',
    color: '#EA580C',
    defaults: { filePath: '', content: '', encoding: 'utf8', appendMode: false },
    schema: [
      { key: 'filePath',   label: 'File Path', type: 'text',
        placeholder: './output/result.json',
        hint: 'Absolute or relative path. Parent directories are created automatically. Supports {{variable}}.' },
      { key: 'content',    label: 'Content',   type: 'textarea',
        placeholder: '{{myVariable}}',
        hint: 'Text or JSON to write. Supports {{variable}} interpolation.' },
      { key: 'appendMode', label: 'Append Mode', type: 'boolean',
        hint: 'When enabled, content is appended instead of overwriting.' },
      { key: 'encoding',   label: 'Encoding',  type: 'text',
        placeholder: 'utf8', hint: 'utf8 (default) | ascii | base64' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'moveFile',
    label: 'Move File',
    category: 'File System',
    description: 'Move or rename a file to a new location',
    iconKey: 'moveFile',
    color: '#EA580C',
    defaults: { sourcePath: '', destinationPath: '' },
    schema: [
      { key: 'sourcePath',      label: 'Source Path',      type: 'text',
        placeholder: './temp/file.txt', hint: 'Path of the file to move. Supports {{variable}}.' },
      { key: 'destinationPath', label: 'Destination Path', type: 'text',
        placeholder: './output/file.txt',
        hint: 'Target path including filename. Parent dirs are created. Supports {{variable}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'deleteFile',
    label: 'Delete File',
    category: 'File System',
    description: 'Delete a file from disk',
    iconKey: 'deleteFile',
    color: '#EA580C',
    defaults: { filePath: '', ignoreNotFound: true },
    schema: [
      { key: 'filePath',       label: 'File Path',           type: 'text',
        placeholder: './temp/file.txt', hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'ignoreNotFound', label: 'Ignore If Not Found', type: 'boolean',
        hint: 'When enabled, no error is thrown if the file does not exist.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'fileExists',
    label: 'File Exists',
    category: 'File System',
    description: 'Check if a file exists; stores true/false',
    iconKey: 'fileExists',
    color: '#EA580C',
    defaults: { filePath: '', outputVariable: 'fileExists' },
    schema: [
      { key: 'filePath',       label: 'File Path',       type: 'text',
        placeholder: './data/input.json', hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'fileExists', hint: 'Stores true or false. Use with IF: {{fileExists == true}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'createDirectory',
    label: 'Create Directory',
    category: 'File System',
    description: 'Create a directory and any missing parents',
    iconKey: 'createDir',
    color: '#EA580C',
    defaults: { directoryPath: '' },
    schema: [
      { key: 'directoryPath', label: 'Directory Path', type: 'text',
        placeholder: './output/reports',
        hint: 'All missing parent directories are created automatically. Supports {{variable}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'directoryExists',
    label: 'Directory Exists',
    category: 'File System',
    description: 'Check if a directory exists; stores true/false',
    iconKey: 'dirExists',
    color: '#EA580C',
    defaults: { directoryPath: '', outputVariable: 'dirExists' },
    schema: [
      { key: 'directoryPath', label: 'Directory Path', type: 'text',
        placeholder: './output', hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'dirExists', hint: 'Stores true or false. Use with IF: {{dirExists == true}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 6 — Excel ───────────────────────────────────────────
  {
    type: 'openExcel',
    label: 'Open Excel',
    category: 'Excel',
    description: 'Open an Excel workbook into the execution context',
    iconKey: 'excelOpen',
    color: '#16A34A',
    defaults: { filePath: '', outputVariable: 'wb', createIfNotExists: false },
    schema: [
      { key: 'filePath',          label: 'File Path',             type: 'text',
        placeholder: './data/report.xlsx',
        hint: 'Absolute or relative path to .xlsx file. Supports {{variable}}.' },
      { key: 'outputVariable',    label: 'Workbook ID Variable',  type: 'text',
        placeholder: 'wb',
        hint: 'Use {{wb}} in all other Excel nodes to reference this workbook.' },
      { key: 'createIfNotExists', label: 'Create If Not Exists',  type: 'boolean',
        hint: 'Create a blank workbook when the file does not exist.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'readCell',
    label: 'Read Cell',
    category: 'Excel',
    description: 'Read a single cell value into a variable',
    iconKey: 'excelReadCell',
    color: '#16A34A',
    defaults: { workbookId: '', sheetName: '', cell: 'A1', outputVariable: 'cellValue' },
    schema: [
      { key: 'workbookId',    label: 'Workbook ID',    type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'sheetName',     label: 'Sheet Name',     type: 'text',
        placeholder: 'Sheet1', hint: 'Leave blank for the first sheet. Supports {{variable}}.' },
      { key: 'cell',          label: 'Cell',           type: 'text',
        placeholder: 'A1', hint: 'A1 notation. Supports {{variable}} e.g. A{{row}}.' },
      { key: 'outputVariable',label: 'Output Variable',type: 'text',
        placeholder: 'cellValue' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'writeCell',
    label: 'Write Cell',
    category: 'Excel',
    description: 'Write a value to a single cell',
    iconKey: 'excelWriteCell',
    color: '#16A34A',
    defaults: { workbookId: '', sheetName: '', cell: 'A1', value: '' },
    schema: [
      { key: 'workbookId', label: 'Workbook ID', type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'sheetName',  label: 'Sheet Name',  type: 'text',
        placeholder: 'Sheet1', hint: 'Leave blank for the first sheet.' },
      { key: 'cell',       label: 'Cell',        type: 'text',
        placeholder: 'B2', hint: 'A1 notation. Supports {{variable}} e.g. B{{row}}.' },
      { key: 'value',      label: 'Value',       type: 'text',
        placeholder: '{{myVariable}}',
        hint: 'Text, number, or {{variable}}. Numeric strings are stored as numbers.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'readRange',
    label: 'Read Range',
    category: 'Excel',
    description: 'Read a cell range into an array (use with For Each)',
    iconKey: 'excelReadRange',
    color: '#16A34A',
    defaults: { workbookId: '', sheetName: '', range: 'A1:D100', outputVariable: 'rows', skipEmptyRows: true },
    schema: [
      { key: 'workbookId',    label: 'Workbook ID',     type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'sheetName',     label: 'Sheet Name',      type: 'text',
        placeholder: 'Sheet1', hint: 'Leave blank for the first sheet.' },
      { key: 'range',         label: 'Range',           type: 'text',
        placeholder: 'A1:D100',
        hint: 'Single column (A2:A100) → flat array. Multi-column → array of arrays.' },
      { key: 'outputVariable',label: 'Output Variable', type: 'text',
        placeholder: 'rows' },
      { key: 'skipEmptyRows', label: 'Skip Empty Rows', type: 'boolean',
        hint: 'Exclude rows with no values from the output array.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'saveExcel',
    label: 'Save Excel',
    category: 'Excel',
    description: 'Save the workbook back to disk',
    iconKey: 'excelSave',
    color: '#16A34A',
    defaults: { workbookId: '', saveAs: '' },
    schema: [
      { key: 'workbookId', label: 'Workbook ID',        type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'saveAs',     label: 'Save As (optional)', type: 'text',
        placeholder: './output/report-copy.xlsx',
        hint: 'Leave blank to overwrite original. Fill to save a copy. Supports {{variable}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'closeExcel',
    label: 'Close Excel',
    category: 'Excel',
    description: 'Release the workbook from memory',
    iconKey: 'excelClose',
    color: '#16A34A',
    defaults: { workbookId: '' },
    schema: [
      { key: 'workbookId', label: 'Workbook ID', type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel. Always close when done.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 7 — Database ─────────────────────────────────────────
  {
    type: 'dbConnect',
    label: 'Connect Database',
    category: 'Database',
    description: 'Open a database connection',
    iconKey: 'dbConnect',
    color: '#6366F1',
    defaults: { connectionName: 'mainDb', databaseType: 'sqlite', databasePath: './data/app.db' },
    schema: [
      { key: 'connectionName', label: 'Connection Name', type: 'text',
        placeholder: 'mainDb',
        hint: 'Identifier used by Query/Execute/Disconnect. Must be unique per run.' },
      { key: 'databaseType', label: 'Database Type', type: 'text',
        placeholder: 'sqlite',
        hint: 'sqlite (MySQL / PostgreSQL planned for future stages).' },
      { key: 'databasePath', label: 'Database Path', type: 'text',
        placeholder: './data/app.db',
        hint: 'Relative or absolute path. Folder is auto-created if missing.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'dbQuery',
    label: 'Query Database',
    category: 'Database',
    description: 'Run SELECT and store results as array',
    iconKey: 'dbQuery',
    color: '#6366F1',
    defaults: { connectionName: 'mainDb', sql: 'SELECT * FROM table_name', outputVariable: 'rows' },
    schema: [
      { key: 'connectionName', label: 'Connection Name', type: 'text', placeholder: 'mainDb' },
      { key: 'sql', label: 'SQL Query', type: 'textarea',
        placeholder: "SELECT * FROM users WHERE status = 'PENDING'",
        hint: 'Use {{variable}} for dynamic values.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'rows',
        hint: 'Array of objects. Use with For Each node.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'dbExecute',
    label: 'Execute Database',
    category: 'Database',
    description: 'Run INSERT, UPDATE, DELETE or DDL',
    iconKey: 'dbExecute',
    color: '#6366F1',
    defaults: { connectionName: 'mainDb', sql: '' },
    schema: [
      { key: 'connectionName', label: 'Connection Name', type: 'text', placeholder: 'mainDb' },
      { key: 'sql', label: 'SQL Statement', type: 'textarea',
        placeholder: "UPDATE vin_queue SET status='DONE' WHERE id={{row.id}}",
        hint: 'INSERT, UPDATE, DELETE, CREATE TABLE. Use {{variable}} for dynamic values. Multiple statements separated by ; are supported.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'dbDisconnect',
    label: 'Disconnect Database',
    category: 'Database',
    description: 'Close a database connection',
    iconKey: 'dbDisconnect',
    color: '#6366F1',
    defaults: { connectionName: 'mainDb' },
    schema: [
      { key: 'connectionName', label: 'Connection Name', type: 'text',
        placeholder: 'mainDb',
        hint: 'Must match the Connection Name used in Connect Database.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ══ Advanced Web Automation Library ════════════════════════════
  // ── Mouse / interaction ──────────────────────────────────────
  {
    type: 'hoverElement', label: 'Hover Element', category: 'Mouse',
    description: 'Hover the mouse over an element', iconKey: 'mouse', color: '#7C3AED',
    defaults: { selector: '' },
    schema: [{ key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#menu', isSelector: true }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'doubleClick', label: 'Double Click', category: 'Mouse',
    description: 'Double-click an element', iconKey: 'mouse', color: '#7C3AED',
    defaults: { selector: '' },
    schema: [{ key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#row', isSelector: true }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'rightClick', label: 'Right Click', category: 'Mouse',
    description: 'Right-click (context menu) an element', iconKey: 'mouse', color: '#7C3AED',
    defaults: { selector: '' },
    schema: [{ key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#item', isSelector: true }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'focusElement', label: 'Focus Element', category: 'Mouse',
    description: 'Move keyboard focus to an element', iconKey: 'mouse', color: '#7C3AED',
    defaults: { selector: '' },
    schema: [{ key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#input', isSelector: true }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'scrollToElement', label: 'Scroll To Element', category: 'Mouse',
    description: 'Scroll until an element is in view', iconKey: 'mouse', color: '#7C3AED',
    defaults: { selector: '' },
    schema: [{ key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#footer', isSelector: true }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'scrollPage', label: 'Scroll Page', category: 'Mouse',
    description: 'Scroll the page up or down by pixels', iconKey: 'mouse', color: '#7C3AED',
    defaults: { direction: 'down', pixels: '600' },
    schema: [
      { key: 'direction', label: 'Direction', type: 'select', options: ['down', 'up'] },
      { key: 'pixels',    label: 'Pixels',    type: 'text', placeholder: '600' },
    ],
    hasInput: true, hasOutput: true,
  },
  // ── Input ────────────────────────────────────────────────────
  {
    type: 'clearInput', label: 'Clear Input', category: 'Input',
    description: 'Clear the value of an input field', iconKey: 'type', color: '#D97706',
    defaults: { selector: '' },
    schema: [{ key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#search', isSelector: true }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'keyboardInput', label: 'Keyboard Input', category: 'Input',
    description: 'Press a key or shortcut (Enter, Ctrl+A…)', iconKey: 'type', color: '#D97706',
    defaults: { key: 'Enter', selector: '' },
    schema: [
      { key: 'key',      label: 'Key / Shortcut', type: 'text', placeholder: 'Enter, Tab, Control+A',
        hint: 'Playwright key syntax. Combine with + (e.g. Control+Shift+S).' },
      { key: 'selector', label: 'Focus Selector (optional)', type: 'text', placeholder: '#input', isSelector: true,
        hint: 'Focus this element before pressing the key.' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'selectDropdown', label: 'Select Dropdown', category: 'Input',
    description: 'Select an option in a <select>', iconKey: 'type', color: '#D97706',
    defaults: { selector: '', by: 'value', value: '' },
    schema: [
      { key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: 'select#country', isSelector: true },
      { key: 'by',       label: 'Match By', type: 'select', options: ['value', 'label', 'index'] },
      { key: 'value',    label: 'Option', type: 'text', placeholder: 'value / label / index', hint: 'Supports {{variable}}.' },
    ],
    hasInput: true, hasOutput: true,
  },
  // ── Element operations ───────────────────────────────────────
  {
    type: 'getAttribute', label: 'Get Attribute', category: 'Browser Get',
    description: 'Read an element attribute into a variable', iconKey: 'getText', color: '#2563EB',
    defaults: { selector: '', attribute: 'href', outputVariable: 'attr' },
    schema: [
      { key: 'selector',       label: 'CSS / XPath Selector', type: 'text', placeholder: 'a.link', isSelector: true },
      { key: 'attribute',      label: 'Attribute', type: 'text', placeholder: 'href, value, class' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'attr' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'setAttribute', label: 'Set Attribute', category: 'Browser Get',
    description: 'Set an attribute on an element', iconKey: 'type', color: '#2563EB',
    defaults: { selector: '', attribute: 'value', value: '' },
    schema: [
      { key: 'selector',  label: 'CSS / XPath Selector', type: 'text', placeholder: '#field', isSelector: true },
      { key: 'attribute', label: 'Attribute', type: 'text', placeholder: 'value, class' },
      { key: 'value',     label: 'Value', type: 'text', placeholder: 'new value', hint: 'Supports {{variable}}.' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'getHtml', label: 'Get HTML', category: 'Browser Get',
    description: 'Read innerHTML/outerHTML of an element', iconKey: 'getText', color: '#2563EB',
    defaults: { selector: '', outer: false, outputVariable: 'html' },
    schema: [
      { key: 'selector',       label: 'CSS / XPath Selector', type: 'text', placeholder: '#content', isSelector: true },
      { key: 'outer',          label: 'Outer HTML', type: 'boolean', hint: 'Include the element tag itself.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'html' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'getValue', label: 'Get Value', category: 'Browser Get',
    description: 'Read the value of an input/select/textarea', iconKey: 'getText', color: '#2563EB',
    defaults: { selector: '', outputVariable: 'value' },
    schema: [
      { key: 'selector',       label: 'CSS / XPath Selector', type: 'text', placeholder: '#email', isSelector: true },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'value' },
    ],
    hasInput: true, hasOutput: true,
  },
  // ── Files ────────────────────────────────────────────────────
  {
    type: 'uploadFile', label: 'Upload File', category: 'Browser Files',
    description: 'Set a file on an <input type=file>', iconKey: 'writeFile', color: '#0891B2',
    defaults: { selector: 'input[type=file]', filePath: '' },
    schema: [
      { key: 'selector', label: 'File Input Selector', type: 'text', placeholder: 'input[type=file]', isSelector: true },
      { key: 'filePath', label: 'File Path', type: 'text', placeholder: 'C:\\data\\report.xlsx', hint: 'Absolute path. Supports {{variable}}.' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'downloadFile', label: 'Download File', category: 'Browser Files',
    description: 'Wait for a download and save it to disk', iconKey: 'readFile', color: '#0891B2',
    defaults: { triggerSelector: '', saveDirectory: '', outputVariable: 'downloadedFilePath', waitForDownload: '30000' },
    schema: [
      { key: 'triggerSelector', label: 'Trigger Selector (optional)', type: 'text', placeholder: 'a.download', isSelector: true,
        hint: 'Clicked while waiting for the download.' },
      { key: 'saveDirectory',   label: 'Save Directory', type: 'text', placeholder: 'C:\\downloads', hint: 'Defaults to your Downloads folder.' },
      { key: 'outputVariable',  label: 'Output Variable', type: 'text', placeholder: 'downloadedFilePath' },
      { key: 'waitForDownload', label: 'Timeout (ms)', type: 'text', placeholder: '30000' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'takeScreenshot', label: 'Take Screenshot', category: 'Browser Files',
    description: 'Capture a screenshot of the page', iconKey: 'exists', color: '#0891B2',
    defaults: { filePath: '', fullPage: false, outputVariable: 'screenshotPath' },
    schema: [
      { key: 'filePath',       label: 'File Path (optional)', type: 'text', placeholder: 'C:\\shots\\page.png', hint: 'Auto-generated if blank.' },
      { key: 'fullPage',       label: 'Full Page', type: 'boolean' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'screenshotPath' },
    ],
    hasInput: true, hasOutput: true,
  },
  // ── Tabs & popups ────────────────────────────────────────────
  {
    type: 'openTab', label: 'Open New Tab', category: 'Browser Tabs',
    description: 'Open a new tab and switch to it', iconKey: 'globe', color: '#2563EB',
    defaults: { url: '', outputVariable: 'tabIndex' },
    schema: [
      { key: 'url',            label: 'URL (optional)', type: 'text', placeholder: 'https://example.com' },
      { key: 'outputVariable', label: 'Tab Index Variable', type: 'text', placeholder: 'tabIndex' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'switchTab', label: 'Switch Tab', category: 'Browser Tabs',
    description: 'Switch the active tab by index', iconKey: 'globe', color: '#2563EB',
    defaults: { index: '0' },
    schema: [{ key: 'index', label: 'Tab Index', type: 'text', placeholder: '0', hint: '0 = first tab.' }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'closeTab', label: 'Close Tab', category: 'Browser Tabs',
    description: 'Close current tab, switch to last remaining', iconKey: 'globe', color: '#DC2626',
    defaults: {},
    schema: [],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'getCurrentTab', label: 'Get Current Tab', category: 'Browser Tabs',
    description: 'Read active tab index, URL and title', iconKey: 'globe', color: '#2563EB',
    defaults: { outputVariable: 'currentTab' },
    schema: [{ key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'currentTab' }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'waitPopup', label: 'Wait Popup', category: 'Browser Tabs',
    description: 'Wait for a popup/new window and switch to it', iconKey: 'waitLoad', color: '#2563EB',
    defaults: { triggerSelector: '', timeout: '15000', outputVariable: 'popupIndex' },
    schema: [
      { key: 'triggerSelector', label: 'Trigger Selector (optional)', type: 'text', placeholder: 'a[target=_blank]', isSelector: true },
      { key: 'timeout',         label: 'Timeout (ms)', type: 'text', placeholder: '15000' },
      { key: 'outputVariable',  label: 'Popup Index Variable', type: 'text', placeholder: 'popupIndex' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'handlePopup', label: 'Handle Popup', category: 'Browser Tabs',
    description: 'Accept/dismiss a JS dialog (alert/confirm/prompt)', iconKey: 'waitLoad', color: '#2563EB',
    defaults: { action: 'accept', promptText: '', triggerSelector: '', timeout: '10000' },
    schema: [
      { key: 'action',          label: 'Action', type: 'select', options: ['accept', 'dismiss'] },
      { key: 'promptText',      label: 'Prompt Text (optional)', type: 'text', placeholder: 'value for window.prompt' },
      { key: 'triggerSelector', label: 'Trigger Selector (optional)', type: 'text', placeholder: '#delete', isSelector: true },
      { key: 'timeout',         label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true, hasOutput: true,
  },
  // ── Frames ───────────────────────────────────────────────────
  {
    type: 'switchFrame', label: 'Switch Frame', category: 'Browser Frame',
    description: 'Enter an iframe so element nodes act inside it', iconKey: 'globe', color: '#0D9488',
    defaults: { frameSelector: '', timeout: '10000' },
    schema: [
      { key: 'frameSelector', label: 'Iframe Selector', type: 'text', placeholder: 'iframe#content', isSelector: true,
        hint: 'Element nodes run inside it until Exit Frame.' },
      { key: 'timeout',       label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'exitFrame', label: 'Exit Frame', category: 'Browser Frame',
    description: 'Return to the main page from an iframe', iconKey: 'globe', color: '#0D9488',
    defaults: {},
    schema: [],
    hasInput: true, hasOutput: true,
  },
  // ── Waits & retry ────────────────────────────────────────────
  {
    type: 'waitUntilVisible', label: 'Wait Until Visible', category: 'Browser Wait',
    description: 'Wait until an element becomes visible', iconKey: 'waitEl', color: '#0EA5E9',
    defaults: { selector: '', timeout: '10000' },
    schema: [
      { key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '#el', isSelector: true },
      { key: 'timeout',  label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'waitUntilHidden', label: 'Wait Until Hidden', category: 'Browser Wait',
    description: 'Wait until an element is hidden/removed', iconKey: 'waitEl', color: '#0EA5E9',
    defaults: { selector: '', timeout: '10000' },
    schema: [
      { key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: '.spinner', isSelector: true },
      { key: 'timeout',  label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'waitUntilEnabled', label: 'Wait Until Enabled', category: 'Browser Wait',
    description: 'Wait until an element is enabled', iconKey: 'waitEl', color: '#0EA5E9',
    defaults: { selector: '', timeout: '10000' },
    schema: [
      { key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: 'button#save', isSelector: true },
      { key: 'timeout',  label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'waitUntilDisabled', label: 'Wait Until Disabled', category: 'Browser Wait',
    description: 'Wait until an element is disabled', iconKey: 'waitEl', color: '#0EA5E9',
    defaults: { selector: '', timeout: '10000' },
    schema: [
      { key: 'selector', label: 'CSS / XPath Selector', type: 'text', placeholder: 'button#submit', isSelector: true },
      { key: 'timeout',  label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'retryUntilSuccess', label: 'Retry Until Success', category: 'Logic',
    description: 'Retry the BODY steps until they succeed', iconKey: 'loop', color: '#D97706',
    defaults: { maxAttempts: '3', interval: '1000' },
    schema: [
      { key: 'maxAttempts', label: 'Max Attempts', type: 'text', placeholder: '3' },
      { key: 'interval',    label: 'Interval (ms)', type: 'text', placeholder: '1000' },
    ],
    hasInput: true, hasOutput: false,
    outputHandles: [
      { id: 'body', label: 'BODY', color: '#D97706' },
      { id: 'done', label: 'DONE', color: '#16A34A' },
    ],
  },
  // ── Web scraping ─────────────────────────────────────────────
  {
    type: 'extractTable', label: 'Extract Table', category: 'Web Scraping',
    description: 'Read an HTML table into an array of objects', iconKey: 'arrLength', color: '#16A34A',
    defaults: { selector: 'table', outputVariable: 'tableData' },
    schema: [
      { key: 'selector',       label: 'Table Selector', type: 'text', placeholder: 'table#data', isSelector: true },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'tableData', hint: 'Array of row objects — use with For Each.' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'extractLinks', label: 'Extract Links', category: 'Web Scraping',
    description: 'Collect links ({text, href}) into an array', iconKey: 'link', color: '#16A34A',
    defaults: { selector: 'a', outputVariable: 'links' },
    schema: [
      { key: 'selector',       label: 'Link Selector', type: 'text', placeholder: 'a', isSelector: true },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'links' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'extractElements', label: 'Extract Elements', category: 'Web Scraping',
    description: 'Collect text/attribute of matching elements', iconKey: 'getText', color: '#16A34A',
    defaults: { selector: '', attribute: '', outputVariable: 'items' },
    schema: [
      { key: 'selector',       label: 'CSS / XPath Selector', type: 'text', placeholder: '.product .name', isSelector: true },
      { key: 'attribute',      label: 'Attribute (optional)', type: 'text', placeholder: 'blank = text content' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'items' },
    ],
    hasInput: true, hasOutput: true,
  },

  // ══ Communication Library (Stage 12) ═══════════════════════════
  {
    type: 'sendEmail', label: 'Send Email', category: 'Communication',
    description: 'Send an email via SMTP (HTML/plain + attachments)', iconKey: 'api', color: '#0EA5E9',
    defaults: { smtpHost: '', smtpPort: '587', secure: false, username: '', password: '', from: '', to: '', cc: '', bcc: '', subject: '', body: '', bodyType: 'html', attachments: '' },
    schema: [
      { key: 'smtpHost',    label: 'SMTP Host', type: 'text', placeholder: 'smtp.gmail.com' },
      { key: 'smtpPort',    label: 'SMTP Port', type: 'text', placeholder: '587' },
      { key: 'secure',      label: 'SSL/TLS (port 465)', type: 'boolean' },
      { key: 'username',    label: 'Username', type: 'text', placeholder: 'user@example.com' },
      { key: 'password',    label: 'Password', type: 'text', placeholder: '{{secret.Mail.password}}', hint: 'Supports {{secret.NAME.password}}.' },
      { key: 'from',        label: 'From', type: 'text', placeholder: 'Bot <bot@example.com>' },
      { key: 'to',          label: 'To', type: 'text', placeholder: 'a@x.com, b@x.com' },
      { key: 'cc',          label: 'Cc', type: 'text', placeholder: 'optional' },
      { key: 'bcc',         label: 'Bcc', type: 'text', placeholder: 'optional' },
      { key: 'subject',     label: 'Subject', type: 'text', placeholder: 'Report ready' },
      { key: 'bodyType',    label: 'Body Type', type: 'select', options: ['html', 'text'] },
      { key: 'body',        label: 'Body', type: 'textarea', placeholder: '<h1>Hi</h1> or plain text. Supports {{variable}}.' },
      { key: 'attachments', label: 'Attachments', type: 'textarea', placeholder: 'C:\\a.pdf, C:\\b.xlsx (one per line or comma-separated)' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'readEmail', label: 'Read Email', category: 'Communication',
    description: 'Read emails from an IMAP mailbox into an array', iconKey: 'log', color: '#0EA5E9',
    defaults: { imapHost: '', imapPort: '993', secure: true, username: '', password: '', folder: 'INBOX', unreadOnly: true, limit: '25', outputVariable: 'emails' },
    schema: [
      { key: 'imapHost',       label: 'IMAP Host', type: 'text', placeholder: 'imap.gmail.com' },
      { key: 'imapPort',       label: 'IMAP Port', type: 'text', placeholder: '993' },
      { key: 'secure',         label: 'SSL/TLS', type: 'boolean' },
      { key: 'username',       label: 'Username', type: 'text', placeholder: 'user@example.com' },
      { key: 'password',       label: 'Password', type: 'text', placeholder: '{{secret.Mail.password}}', hint: 'Supports {{secret.NAME.password}}.' },
      { key: 'folder',         label: 'Folder', type: 'text', placeholder: 'INBOX' },
      { key: 'unreadOnly',     label: 'Unread Only', type: 'boolean' },
      { key: 'limit',          label: 'Max Emails', type: 'text', placeholder: '25' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'emails', hint: 'Array of email objects — use with For Each.' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'saveAttachment', label: 'Save Attachment', category: 'Communication',
    description: 'Save attachments of an email (or array) to disk', iconKey: 'writeFile', color: '#0EA5E9',
    defaults: { emailVariable: '{{item}}', saveDirectory: '', outputVariable: 'savedFiles' },
    schema: [
      { key: 'emailVariable',  label: 'Email Variable', type: 'text', placeholder: '{{item}}', hint: 'An email object (from For Each) or array of emails.' },
      { key: 'saveDirectory',  label: 'Save Directory', type: 'text', placeholder: 'C:\\attachments' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text', placeholder: 'savedFiles' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'moveEmail', label: 'Move Email', category: 'Communication',
    description: 'Move an email to another folder', iconKey: 'moveFile', color: '#0EA5E9',
    defaults: { emailId: '{{item.id}}', targetFolder: 'Archive' },
    schema: [
      { key: 'emailId',      label: 'Email Id (uid)', type: 'text', placeholder: '{{item.id}}' },
      { key: 'targetFolder', label: 'Target Folder', type: 'text', placeholder: 'Archive' },
    ],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'markEmailRead', label: 'Mark Email Read', category: 'Communication',
    description: 'Flag an email as read', iconKey: 'fileExists', color: '#0EA5E9',
    defaults: { emailId: '{{item.id}}' },
    schema: [{ key: 'emailId', label: 'Email Id (uid)', type: 'text', placeholder: '{{item.id}}' }],
    hasInput: true, hasOutput: true,
  },
  {
    type: 'deleteEmail', label: 'Delete Email', category: 'Communication',
    description: 'Delete an email from the mailbox', iconKey: 'deleteFile', color: '#DC2626',
    defaults: { emailId: '{{item.id}}' },
    schema: [{ key: 'emailId', label: 'Email Id (uid)', type: 'text', placeholder: '{{item.id}}' }],
    hasInput: true, hasOutput: true,
  },
];

export function getNodesByCategory() {
  const categories = {};
  for (const def of NODE_DEFINITIONS) {
    if (!categories[def.category]) categories[def.category] = [];
    categories[def.category].push(def);
  }
  return categories;
}

export function getNodeDefinition(type) {
  return NODE_DEFINITIONS.find(d => d.type === type) || null;
}
