/**
 * Node type definitions for the workflow designer.
 * Maps to the engine plugin system.
 */

export const NODE_DEFINITIONS = [
  {
    type: 'start',
    label: 'Start',
    category: 'Flow Control',
    description: 'Workflow entry point',
    iconKey: 'play',
    color: '#16A34A',
    defaults: {},
    schema: [],
    maxInstances: 1,
    hasInput: false,
    hasOutput: true,
  },
  {
    type: 'openBrowser',
    label: 'Open Browser',
    category: 'Browser',
    description: 'Launch a browser instance',
    iconKey: 'globe',
    color: '#2563EB',
    defaults: { headless: false },
    schema: [
      { key: 'headless', label: 'Headless Mode', type: 'boolean' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'navigateUrl',
    label: 'Navigate URL',
    category: 'Browser',
    description: 'Go to a web address',
    iconKey: 'link',
    color: '#7C3AED',
    defaults: { url: 'https://example.com' },
    schema: [
      { key: 'url', label: 'URL', type: 'text', placeholder: 'https://example.com' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'inputText',
    label: 'Input Text',
    category: 'Input',
    description: 'Type into an input field',
    iconKey: 'type',
    color: '#D97706',
    defaults: { selector: '', value: '', clearFirst: true },
    schema: [
      { key: 'selector',   label: 'CSS Selector',    type: 'text',    placeholder: '#username', isSelector: true },
      { key: 'value',      label: 'Value',            type: 'text',    placeholder: 'Enter text...' },
      { key: 'clearFirst', label: 'Clear Field First',type: 'boolean' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'clickElement',
    label: 'Click Element',
    category: 'Mouse',
    description: 'Click a page element',
    iconKey: 'mouse',
    color: '#7C3AED',
    defaults: { selector: '', doubleClick: false, waitNavigation: false },
    schema: [
      { key: 'selector',       label: 'CSS Selector',       type: 'text',    placeholder: '#login-button', isSelector: true },
      { key: 'doubleClick',    label: 'Double Click',        type: 'boolean' },
      { key: 'waitNavigation', label: 'Wait for Navigation', type: 'boolean',
        hint: 'Enable when this click triggers a redirect or page reload.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'end',
    label: 'End',
    category: 'Flow Control',
    description: 'Workflow end point',
    iconKey: 'stop',
    color: '#6B7280',
    defaults: { autoCloseBrowser: true, restoreWindow: true },
    schema: [
      { key: 'autoCloseBrowser', label: 'Auto Close Browser',    type: 'boolean',
        hint: 'When disabled, the browser stays open after the workflow finishes.' },
      { key: 'restoreWindow',    label: 'Restore Cyclone Window', type: 'boolean',
        hint: 'Bring Cyclone back to the foreground after execution.' },
    ],
    maxInstances: 1,
    hasInput: true,
    hasOutput: false,
  },

  // ── Stage 2 nodes ─────────────────────────────────────────
  {
    type: 'setVariable',
    label: 'Set Variable',
    category: 'Logic',
    description: 'Assign a value to a workflow variable',
    iconKey: 'variable',
    color: '#16A34A',
    defaults: { variableName: '', value: '' },
    schema: [
      { key: 'variableName', label: 'Variable Name', type: 'text',
        placeholder: 'username' },
      { key: 'value', label: 'Value', type: 'text',
        placeholder: 'admin',
        hint: 'Plain text, {{variable}}, or typed literals: {{[1,2,3]}} {{true}} {{42}} {{response.data}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'logMessage',
    label: 'Log Message',
    category: 'Logic',
    description: 'Print a message to the execution console',
    iconKey: 'log',
    color: '#6B7280',
    defaults: { message: '', level: 'INFO' },
    schema: [
      { key: 'message', label: 'Message', type: 'textarea',
        placeholder: 'Hello, {{username}}',
        hint: 'Supports {{variable}} and {{obj.nested}} interpolation.' },
      { key: 'level', label: 'Level', type: 'text',
        placeholder: 'INFO',
        hint: 'INFO, WARN, ERROR, or SUCCESS.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'delay',
    label: 'Delay',
    category: 'Logic',
    description: 'Pause execution for a number of milliseconds',
    iconKey: 'clock',
    color: '#D97706',
    defaults: { milliseconds: '1000' },
    schema: [
      { key: 'milliseconds', label: 'Milliseconds', type: 'text',
        placeholder: '1000',
        hint: 'Supports {{variable}} — resolved at runtime.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'httpRequest',
    label: 'HTTP Request',
    category: 'API',
    description: 'Make an HTTP call and store the response',
    iconKey: 'api',
    color: '#2563EB',
    defaults: { method: 'GET', url: '', headers: '', body: '', outputVariable: 'response' },
    schema: [
      { key: 'method', label: 'Method', type: 'text',
        placeholder: 'GET' },
      { key: 'url', label: 'URL', type: 'text',
        placeholder: 'https://api.example.com/users/{{userId}}',
        hint: 'Supports {{variable}} interpolation.' },
      { key: 'headers', label: 'Headers (JSON)', type: 'textarea',
        placeholder: '{"Authorization": "Bearer {{token}}"}',
        hint: 'Optional JSON object. Supports {{variable}}.' },
      { key: 'body', label: 'Body (JSON)', type: 'textarea',
        placeholder: '{"username": "{{username}}"}',
        hint: 'Used for POST / PUT / PATCH. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'response',
        hint: 'Access response data with {{response.data.id}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 3 nodes ─────────────────────────────────────────
  {
    type: 'ifNode',
    label: 'IF',
    category: 'Logic',
    description: 'Branch workflow based on a condition',
    iconKey: 'condition',
    color: '#7C3AED',
    defaults: { condition: '' },
    schema: [
      { key: 'condition', label: 'Condition', type: 'text',
        placeholder: '{{response.status == 200}}',
        hint: 'Supports {{variable}} expressions. Routes to TRUE or FALSE branch.' },
    ],
    hasInput: true,
    hasOutput: false,
    outputHandles: [
      { id: 'true',  label: 'TRUE',  color: '#16A34A' },
      { id: 'false', label: 'FALSE', color: '#DC2626' },
    ],
  },
  {
    type: 'forEachNode',
    label: 'For Each',
    category: 'Logic',
    description: 'Iterate over each item in a collection',
    iconKey: 'loop',
    color: '#2563EB',
    defaults: { collection: '', itemVariable: 'item' },
    schema: [
      { key: 'collection',   label: 'Collection',   type: 'text',
        placeholder: '{{users}}',
        hint: 'Variable containing an array. Use {{variable}} syntax.' },
      { key: 'itemVariable', label: 'Item Variable', type: 'text',
        placeholder: 'item',
        hint: 'Name for each element (e.g. access with {{item.name}}).' },
    ],
    hasInput: true,
    hasOutput: false,
    outputHandles: [
      { id: 'body', label: 'BODY', color: '#2563EB' },
      { id: 'done', label: 'DONE', color: '#16A34A' },
    ],
  },
  {
    type: 'tryCatchNode',
    label: 'Try / Catch',
    category: 'Logic',
    description: 'Handle errors without stopping the workflow',
    iconKey: 'shield',
    color: '#D97706',
    defaults: { errorVariable: 'lastError' },
    schema: [
      { key: 'errorVariable', label: 'Error Variable', type: 'text',
        placeholder: 'lastError',
        hint: 'Variable that stores the error message if TRY fails.' },
    ],
    hasInput: true,
    hasOutput: false,
    outputHandles: [
      { id: 'try',   label: 'TRY',   color: '#16A34A' },
      { id: 'catch', label: 'CATCH', color: '#DC2626' },
    ],
  },

  // ── Stage 4A — Browser Wait ────────────────────────────────
  {
    type: 'waitUrl',
    label: 'Wait URL',
    category: 'Browser Wait',
    description: 'Wait until the page URL contains the expected value',
    iconKey: 'waitUrl',
    color: '#7C3AED',
    defaults: { expectedUrl: '', timeout: '15000' },
    schema: [
      { key: 'expectedUrl', label: 'Expected URL', type: 'text',
        placeholder: 'https://example.com/success',
        hint: 'Partial match — waits until current URL contains this string. Supports {{variable}}.' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'text', placeholder: '15000' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'waitElement',
    label: 'Wait Element',
    category: 'Browser Wait',
    description: 'Wait until an element reaches a specific state',
    iconKey: 'waitEl',
    color: '#7C3AED',
    defaults: { selector: '', state: 'visible', timeout: '10000' },
    schema: [
      { key: 'selector', label: 'CSS Selector', type: 'text',
        placeholder: '#success-message', isSelector: true },
      { key: 'state',    label: 'State',        type: 'text',
        placeholder: 'visible', hint: 'visible | attached | hidden | detached' },
      { key: 'timeout',  label: 'Timeout (ms)', type: 'text', placeholder: '10000' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'waitPageLoad',
    label: 'Wait Page Load',
    category: 'Browser Wait',
    description: 'Wait for the page to reach a specific load state',
    iconKey: 'waitLoad',
    color: '#7C3AED',
    defaults: { state: 'domcontentloaded', timeout: '30000' },
    schema: [
      { key: 'state',   label: 'Load State',   type: 'text',
        placeholder: 'domcontentloaded', hint: 'load | domcontentloaded | networkidle' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'text', placeholder: '30000' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 4A — Browser Get ─────────────────────────────────
  {
    type: 'getCurrentUrl',
    label: 'Get Current URL',
    category: 'Browser Get',
    description: 'Store the current page URL in a workflow variable',
    iconKey: 'getUrl',
    color: '#2563EB',
    defaults: { outputVariable: 'currentUrl' },
    schema: [
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'currentUrl', hint: 'Access with {{currentUrl}} in later nodes.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'getText',
    label: 'Get Text',
    category: 'Browser Get',
    description: 'Extract visible text from an element into a variable',
    iconKey: 'getText',
    color: '#2563EB',
    defaults: { selector: '', outputVariable: 'text', timeout: '10000' },
    schema: [
      { key: 'selector',      label: 'CSS Selector',   type: 'text',
        placeholder: 'h1.post-title', isSelector: true },
      { key: 'outputVariable',label: 'Output Variable', type: 'text',
        placeholder: 'text', hint: 'Access extracted text with {{text}} in later nodes.' },
      { key: 'timeout',       label: 'Timeout (ms)',    type: 'text', placeholder: '10000' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'elementExists',
    label: 'Element Exists',
    category: 'Browser Get',
    description: 'Check if an element exists, store true/false in a variable',
    iconKey: 'exists',
    color: '#16A34A',
    defaults: { selector: '', outputVariable: 'elementExists' },
    schema: [
      { key: 'selector',      label: 'CSS Selector',   type: 'text',
        placeholder: '#error-message', isSelector: true },
      { key: 'outputVariable',label: 'Output Variable', type: 'text',
        placeholder: 'elementExists', hint: 'Use with IF: {{elementExists == true}}' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 5 — Data Processing ──────────────────────────────
  {
    type: 'jsonParse',
    label: 'JSON Parse',
    category: 'Data Processing',
    description: 'Parse a JSON string into an object or array',
    iconKey: 'jsonParse',
    color: '#0891B2',
    defaults: { input: '', outputVariable: 'jsonData' },
    schema: [
      { key: 'input',          label: 'JSON Input',      type: 'text',
        placeholder: '{{response.raw}}',
        hint: 'Variable or text containing a valid JSON string. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'jsonData',
        hint: 'Access with {{jsonData.key}} or {{jsonData.0.name}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'stringReplace',
    label: 'String Replace',
    category: 'Data Processing',
    description: 'Replace all occurrences of a substring',
    iconKey: 'strReplace',
    color: '#0891B2',
    defaults: { input: '', search: '', replace: '', outputVariable: 'result' },
    schema: [
      { key: 'input',          label: 'Input String',    type: 'text',
        placeholder: '{{someVariable}}',
        hint: 'Source string. Supports {{variable}}.' },
      { key: 'search',         label: 'Search',          type: 'text',
        placeholder: '-',
        hint: 'All occurrences of this substring are replaced.' },
      { key: 'replace',        label: 'Replace With',    type: 'text',
        placeholder: '',
        hint: 'Replacement text. Leave blank to delete the matched substring.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'result' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'stringContains',
    label: 'String Contains',
    category: 'Data Processing',
    description: 'Check if a string contains a substring; stores true/false',
    iconKey: 'strContains',
    color: '#0891B2',
    defaults: { input: '', search: '', caseSensitive: true, outputVariable: 'containsResult' },
    schema: [
      { key: 'input',          label: 'Input String',    type: 'text',
        placeholder: '{{someVariable}}',
        hint: 'Source string to search within. Supports {{variable}}.' },
      { key: 'search',         label: 'Search For',      type: 'text',
        placeholder: 'hello' },
      { key: 'caseSensitive',  label: 'Case Sensitive',  type: 'boolean' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'containsResult',
        hint: 'Stores true or false. Use with IF: {{containsResult == true}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'dateTimeFormat',
    label: 'Date Time Format',
    category: 'Data Processing',
    description: 'Parse and reformat a date/time string',
    iconKey: 'dateTime',
    color: '#0891B2',
    defaults: { inputDate: '', inputFormat: '', outputFormat: 'DD/MM/YYYY', outputVariable: 'formattedDate' },
    schema: [
      { key: 'inputDate',      label: 'Input Date',      type: 'text',
        placeholder: '2026-06-15',
        hint: 'Supports {{variable}}. ISO format is auto-detected when Input Format is blank.' },
      { key: 'inputFormat',    label: 'Input Format',    type: 'text',
        placeholder: 'YYYY-MM-DD',
        hint: 'Tokens: YYYY MM DD HH mm ss. Leave blank to auto-parse.' },
      { key: 'outputFormat',   label: 'Output Format',   type: 'text',
        placeholder: 'DD/MM/YYYY',
        hint: 'Tokens: YYYY MM DD HH mm ss.  e.g. DD/MM/YYYY HH:mm' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'formattedDate' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'arrayLength',
    label: 'Array Length',
    category: 'Data Processing',
    description: 'Get the number of items in an array',
    iconKey: 'arrLength',
    color: '#0891B2',
    defaults: { inputArray: '', outputVariable: 'arrayLength' },
    schema: [
      { key: 'inputArray',     label: 'Input Array',     type: 'text',
        placeholder: '{{users}}',
        hint: 'Variable containing an array. Use {{variableName}} syntax.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'arrayLength',
        hint: 'Stores the count as a number. Use with IF: {{arrayLength > 0}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 5 — File System ──────────────────────────────────
  {
    type: 'readFile',
    label: 'Read File',
    category: 'File System',
    description: 'Read file contents into a variable',
    iconKey: 'readFile',
    color: '#EA580C',
    defaults: { filePath: '', encoding: 'utf8', outputVariable: 'fileContent' },
    schema: [
      { key: 'filePath',       label: 'File Path',       type: 'text',
        placeholder: './data/input.json',
        hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'encoding',       label: 'Encoding',        type: 'text',
        placeholder: 'utf8', hint: 'utf8 (default) | ascii | base64 | binary' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'fileContent',
        hint: 'File contents stored as a string. Combine with JSON Parse for JSON files.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'writeFile',
    label: 'Write File',
    category: 'File System',
    description: 'Write or append content to a file',
    iconKey: 'writeFile',
    color: '#EA580C',
    defaults: { filePath: '', content: '', encoding: 'utf8', appendMode: false },
    schema: [
      { key: 'filePath',   label: 'File Path', type: 'text',
        placeholder: './output/result.json',
        hint: 'Absolute or relative path. Parent directories are created automatically. Supports {{variable}}.' },
      { key: 'content',    label: 'Content',   type: 'textarea',
        placeholder: '{{myVariable}}',
        hint: 'Text or JSON to write. Supports {{variable}} interpolation.' },
      { key: 'appendMode', label: 'Append Mode', type: 'boolean',
        hint: 'When enabled, content is appended instead of overwriting.' },
      { key: 'encoding',   label: 'Encoding',  type: 'text',
        placeholder: 'utf8', hint: 'utf8 (default) | ascii | base64' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'moveFile',
    label: 'Move File',
    category: 'File System',
    description: 'Move or rename a file to a new location',
    iconKey: 'moveFile',
    color: '#EA580C',
    defaults: { sourcePath: '', destinationPath: '' },
    schema: [
      { key: 'sourcePath',      label: 'Source Path',      type: 'text',
        placeholder: './temp/file.txt', hint: 'Path of the file to move. Supports {{variable}}.' },
      { key: 'destinationPath', label: 'Destination Path', type: 'text',
        placeholder: './output/file.txt',
        hint: 'Target path including filename. Parent dirs are created. Supports {{variable}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'deleteFile',
    label: 'Delete File',
    category: 'File System',
    description: 'Delete a file from disk',
    iconKey: 'deleteFile',
    color: '#EA580C',
    defaults: { filePath: '', ignoreNotFound: true },
    schema: [
      { key: 'filePath',       label: 'File Path',           type: 'text',
        placeholder: './temp/file.txt', hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'ignoreNotFound', label: 'Ignore If Not Found', type: 'boolean',
        hint: 'When enabled, no error is thrown if the file does not exist.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'fileExists',
    label: 'File Exists',
    category: 'File System',
    description: 'Check if a file exists; stores true/false',
    iconKey: 'fileExists',
    color: '#EA580C',
    defaults: { filePath: '', outputVariable: 'fileExists' },
    schema: [
      { key: 'filePath',       label: 'File Path',       type: 'text',
        placeholder: './data/input.json', hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'fileExists', hint: 'Stores true or false. Use with IF: {{fileExists == true}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'createDirectory',
    label: 'Create Directory',
    category: 'File System',
    description: 'Create a directory and any missing parents',
    iconKey: 'createDir',
    color: '#EA580C',
    defaults: { directoryPath: '' },
    schema: [
      { key: 'directoryPath', label: 'Directory Path', type: 'text',
        placeholder: './output/reports',
        hint: 'All missing parent directories are created automatically. Supports {{variable}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'directoryExists',
    label: 'Directory Exists',
    category: 'File System',
    description: 'Check if a directory exists; stores true/false',
    iconKey: 'dirExists',
    color: '#EA580C',
    defaults: { directoryPath: '', outputVariable: 'dirExists' },
    schema: [
      { key: 'directoryPath', label: 'Directory Path', type: 'text',
        placeholder: './output', hint: 'Absolute or relative path. Supports {{variable}}.' },
      { key: 'outputVariable', label: 'Output Variable', type: 'text',
        placeholder: 'dirExists', hint: 'Stores true or false. Use with IF: {{dirExists == true}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },

  // ── Stage 6 — Excel ───────────────────────────────────────────
  {
    type: 'openExcel',
    label: 'Open Excel',
    category: 'Excel',
    description: 'Open an Excel workbook into the execution context',
    iconKey: 'excelOpen',
    color: '#16A34A',
    defaults: { filePath: '', outputVariable: 'wb', createIfNotExists: false },
    schema: [
      { key: 'filePath',          label: 'File Path',             type: 'text',
        placeholder: './data/report.xlsx',
        hint: 'Absolute or relative path to .xlsx file. Supports {{variable}}.' },
      { key: 'outputVariable',    label: 'Workbook ID Variable',  type: 'text',
        placeholder: 'wb',
        hint: 'Use {{wb}} in all other Excel nodes to reference this workbook.' },
      { key: 'createIfNotExists', label: 'Create If Not Exists',  type: 'boolean',
        hint: 'Create a blank workbook when the file does not exist.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'readCell',
    label: 'Read Cell',
    category: 'Excel',
    description: 'Read a single cell value into a variable',
    iconKey: 'excelReadCell',
    color: '#16A34A',
    defaults: { workbookId: '', sheetName: '', cell: 'A1', outputVariable: 'cellValue' },
    schema: [
      { key: 'workbookId',    label: 'Workbook ID',    type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'sheetName',     label: 'Sheet Name',     type: 'text',
        placeholder: 'Sheet1', hint: 'Leave blank for the first sheet. Supports {{variable}}.' },
      { key: 'cell',          label: 'Cell',           type: 'text',
        placeholder: 'A1', hint: 'A1 notation. Supports {{variable}} e.g. A{{row}}.' },
      { key: 'outputVariable',label: 'Output Variable',type: 'text',
        placeholder: 'cellValue' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'writeCell',
    label: 'Write Cell',
    category: 'Excel',
    description: 'Write a value to a single cell',
    iconKey: 'excelWriteCell',
    color: '#16A34A',
    defaults: { workbookId: '', sheetName: '', cell: 'A1', value: '' },
    schema: [
      { key: 'workbookId', label: 'Workbook ID', type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'sheetName',  label: 'Sheet Name',  type: 'text',
        placeholder: 'Sheet1', hint: 'Leave blank for the first sheet.' },
      { key: 'cell',       label: 'Cell',        type: 'text',
        placeholder: 'B2', hint: 'A1 notation. Supports {{variable}} e.g. B{{row}}.' },
      { key: 'value',      label: 'Value',       type: 'text',
        placeholder: '{{myVariable}}',
        hint: 'Text, number, or {{variable}}. Numeric strings are stored as numbers.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'readRange',
    label: 'Read Range',
    category: 'Excel',
    description: 'Read a cell range into an array (use with For Each)',
    iconKey: 'excelReadRange',
    color: '#16A34A',
    defaults: { workbookId: '', sheetName: '', range: 'A1:D100', outputVariable: 'rows', skipEmptyRows: true },
    schema: [
      { key: 'workbookId',    label: 'Workbook ID',     type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'sheetName',     label: 'Sheet Name',      type: 'text',
        placeholder: 'Sheet1', hint: 'Leave blank for the first sheet.' },
      { key: 'range',         label: 'Range',           type: 'text',
        placeholder: 'A1:D100',
        hint: 'Single column (A2:A100) → flat array. Multi-column → array of arrays.' },
      { key: 'outputVariable',label: 'Output Variable', type: 'text',
        placeholder: 'rows' },
      { key: 'skipEmptyRows', label: 'Skip Empty Rows', type: 'boolean',
        hint: 'Exclude rows with no values from the output array.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'saveExcel',
    label: 'Save Excel',
    category: 'Excel',
    description: 'Save the workbook back to disk',
    iconKey: 'excelSave',
    color: '#16A34A',
    defaults: { workbookId: '', saveAs: '' },
    schema: [
      { key: 'workbookId', label: 'Workbook ID',        type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel.' },
      { key: 'saveAs',     label: 'Save As (optional)', type: 'text',
        placeholder: './output/report-copy.xlsx',
        hint: 'Leave blank to overwrite original. Fill to save a copy. Supports {{variable}}.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
  {
    type: 'closeExcel',
    label: 'Close Excel',
    category: 'Excel',
    description: 'Release the workbook from memory',
    iconKey: 'excelClose',
    color: '#16A34A',
    defaults: { workbookId: '' },
    schema: [
      { key: 'workbookId', label: 'Workbook ID', type: 'text',
        placeholder: '{{wb}}', hint: 'Workbook ID from Open Excel. Always close when done.' },
    ],
    hasInput: true,
    hasOutput: true,
  },
];

export function getNodesByCategory() {
  const categories = {};
  for (const def of NODE_DEFINITIONS) {
    if (!categories[def.category]) categories[def.category] = [];
    categories[def.category].push(def);
  }
  return categories;
}

export function getNodeDefinition(type) {
  return NODE_DEFINITIONS.find(d => d.type === type) || null;
}
